### PR TITLE
Small Refresh

### PR DESCRIPTION
**Pull request by chk18**
Moved old files to a new archive folder, and added fresh folders and files for kids today

### CODE REVIEW

**Review by wray — CHANGES_REQUESTED** [review]
Don't check in .pyc files into source control. Please remove them from the branch. You should go ahead and delete all the previous student files -- archiving in git is redundant. They are already archived in the repo history.

**Comment by chk18** [comment]
It's working on the Pi, I just need to enable the cron job once it gets merged and gets pushed up to PyPi

**Comment by wray** [comment]
Please see my comments and requested changes. And if you have additional code for the other GPIO accessories, please add that or start a new repo.

**Comment by chk18** [comment]
I think this project is pretty much a wrap. Just need to do some final testing with the whole deployment pipeline. The cron job is running correctly, albeit not working because of changes but once PyPi has the latest code it should _work_ 

There are two bugs that I know of right now:

- Temp/Humidity sensor won't work, it works local but within the Slackbot it gives an error. 
- At the end of the response from the bot, a <class 'NameError'> is left

I've tried to figure these out but I haven't gotten anywhere. It's frustrating because getting everything to work and run and do what you want locally has been easy haha. It's incorporating it into the Slackbot that has just given me a bunch of <class > errors

Will need to practice my debugging

**Comment by wray** [comment]
And that is a big reason for devops/ci/cd -- being able to repeat and retest an application in the actual target environment. Just don't use that excuse if you are on a dev team unless you want to get flamed, "Works for Me".

**Comment by wray** [comment]
Also, does ./unittests run for you locally? It won't as is.

**Comment by wray** [comment]
The issues here are all kind of modularity type issues... Too much is tied into too few modules without separate functions or classes. You do need to decide what constitutes a valid test for travis vs. what you want to test locally (on your laptop) vs what to actually test on a pi. The key is that you want to be able to run unittests that either self-determine or use flags for the environment.
You don't want to be impractical and try and force travis to test things that won't really make sense until it is on a pi -- so clear those up so the build can continue and install. You can look at actually having travis spin up a rpi image (that may already exist) to do more thorough testing, but we can also just use the actually c/i system to get code out to the pis to test where it matters!
There are all kinds of tricks to stubbing out modules or deferring import until actually needed and this will force you to write your code better to enable such things easily.
A lot of this just comes with practice and doing but also a better understanding of the language in terms of library dependencies and scoping. And this is actually a bit harder with an interpreted language like Python where these things can be done runtime and on the fly. Working with compiled languages is actually helpful in this respect as you get a better feel for static dependencies and library linking at compile time -- that is super helpful to then sort out how the more dynamic languages resolve dependencies on the fly.

**Comment by wray** [comment]
Also, BTW and FYI:
When using <= python3.5, the default slackclient will be <= 2.0.0 . The slackclient changed a lot in v2.0.0+. So, if you use python3.6, it will require an upgrade to our code to work with the upgraded API. Nothing big, but that was another issue I found trying to get Travis buildling/testing in the correct python and slackclient environment.

**Comment by wray** [comment]
And you will need to retest your stuff after my changes -- you may need to alter some things, but hopefully you get the jist of what I did to defer dependencies until actually needed.

**Review by wray — CHANGES_REQUESTED** [review]
Please see all my comments. This code is passing contrived tests and deploying to pypi. You need to make sure the GPIO stuff still works -- you may need to react to some of my changes since that code is actually won't be exercised until on the pi.
I would suggest we get the basics/leds working in this branch -- with everything clean and round trip to the pi so we can close and merge this branch and then open up a new one to work the temp/humidity issues.

**Pull request merged**
